<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => '内容',
    'Entity' => '实体',
    'Entity ID' => '实体ID',
    'Parent ID' => '父级ID',
    'Status' => '状态',
    'Level' => '层级',
    'Created by' => '创建者',
    'Updated by' => '更新者',
    'Related to' => '相关于',
    'Url' => 'Url',
    'Created date' => '创建日期时间',
    'Updated date' => '更新日期时间',
    'View' => '查看',
    'Update' => '更新',
    'Delete' => '删除',
    'Reply' => '回复',
    'Comments ({0})' => '评论 ({0})',
    'Comment cannot be blank.' => '评论不能为空。',
    'Comment has not been deleted. Please try again!' => '该评论已经被删除。请再试一次！',
    'Add a comment...' => '说点什么吧...',
    'Comment' => '评论',
    'Oops, something went wrong. Please try again later.' => '出现错误！请再试一次。',
    'The requested page does not exist.' => '请求的页面不存在。',
    'Comment has been deleted.' => '该评论已经被删除。',
    'Comment has been saved.' => '该评论已经被保存。',
    'Click here to cancel reply.' => '取消回复。',
    'Comments Management' => '评论管理',
    'Select Status' => '请选择状态',
    'Select Author' => '请选择发布者',
    'Update Comment: {0}' => '更新评论：{0}',
    'Active' => '激活',
    'Deleted' => '已删除',
    'Go Back' => '返回',

    ///\vendor\yongtiger\yii2-comment\src\widgets\views\index.php
    'Latest' => '最新评论',
    'Earliest' => '最早评论',
    'Most Vote Up' => '最多好评',
    'Less Vote Up' => '最少好评',
    'Most Vote Down' => '最多差评',
    'Less Vote Down' => '最少差评',
    '(no comments)' => '(还没有评论)',

    ///\vendor\yongtiger\yii2-comment\src\controllers\DefaultController.php
    'No Permission to vote!' => '没有投票权限！',
    'Invalid vote input.' => '无效投票操作！',

];
